server:
  port: 8088
  
nutri:
  base:
    url: http://localhost:8081/addressApp/api/

spring:
  application:
     name: securityJWT
  datasource:
    url: jdbc:mysql://localhost:3306/aipsnutricalc
    username: root
    password: Merda1
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # o il valore che preferisci
  
  